### PR TITLE
Fixing OSX and MPI_AGGREGATE bugs

### PR DESCRIPTION
**Pull request by khuck**
Fixing ADIOST interface bugs that affected OSX builds and the MPI_AGGREGATE method.

### CODE REVIEW

**Comment by pnorbert** [comment]
The build fails for me on Lubuntu 64bit:

make[3]: Entering directory '/home/adios/work/ADIOS/build/src'
mpicc -DHAVE_CONFIG_H -I. -I../../src -I..  -I../src/public -I../.. -I../../src/core -I../../src/core/transforms -I../../src/core/query -D_NOMPI -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_GNU_SOURCE  -I../../src/mxml/mxml-2.9 -DZFP  -I../../src/zfp/zfp-0.5.0/inc -D_NOMPI -I/opt/chaos/include -DZLIB  -DBZIP2  -DLZ4  -DBLOSC -I/opt/blosc/include -I/opt/SZ/include -DISOBAR -I/opt/isobar/include -DALACRITY -I/opt/alacrity/include -DFASTBIT -I/opt/fastbit/include/fastbit   -I/opt/chaos/include     -I/opt/blosc/include      -g -O0 -fPIC -Wno-int-to-pointer-cast -Wno-pointer-to-int-cast -c -o core/libcoreonce_a-adiost_callback_internal.o `test -f 'core/adiost_callback_internal.c' || echo '../../src/'`core/adiost_callback_internal.c
In file included from ../../src/core/adiost_callback_internal.h:30:0,
                 from ../../src/core/adiost_callback_internal.c:8:
../../src/public/adiost_callback_api.h:676:47: error: adiost_tool declared weak after being used
 ADIOST_EXPORT adiost_initialize_t ADIOST_WEAK adiost_tool(void);
                                               ^~~~~~~~~~~
Makefile:5196: recipe for target 'core/libcoreonce_a-adiost_callback_internal.o' failed

**Comment by khuck** [comment]
Interesting - it worked OK on two other systems...but shouldn't have.  Testing another fix...

**Comment by khuck** [comment]
OK, it should build on all systems now.

**Comment by jychoi-hpc** [comment]
This fix works on my mac now. Thank you for the fix.

**Pull request merged**
