### PR TITLE
fix cmake compile

### LINKED ISSUE #103: cmake compile broken
If I compile adios with the help of `cmake` is is not compiling:
- build in mxml library problems (missing header include)
- many times `mpi.h` is missing 

I compile with gcc 4.9.2 and openMPI 1.8.6 on a ubuntu 14.04 HPC cluster. But I am not using the mpicc wrapper.

### PR DESCRIPTION
**Pull request by psychocoderHPC**
close #103

- fix missing `mpi.h` by adding cflags to
  - tests
  - utils
  - examples
- fix that `ADIOSLIB_LDADD` is linked to read only executables (use `ADIOSREADLIB_LDADD` instead)
- fix missing `pthread` library by adding to `ADIOS*SLIB_*`  and `ADIOSLIB_LDADD`
- add mpi flags to each programm which links against mpi
- add missing pthread library to adios
- fix `global_range_select/array_[writer|reader]`

**Test**
- [x] compile with cmake without mpicc (used gcc 4.9.2)

### CODE REVIEW

**Comment by pnorbert** [comment]
This branch does not build with my standard MPI settings on Ubuntu 16.04 LTS + openmpi. The -I option with many paths concatenated with ; throws off the compile command. 

[  3%] Building C object src/CMakeFiles/adios_internal_nompi.dir/core/mpidummy.c.o
cd /home/adios/work/ADIOS/build.cmake/src && /usr/bin/mpicc   -I/home/adios/work/ADIOS -I/home/adios/work/ADIOS/src/zfp/zfp-0.5.0/inc -I/home/adios/work/ADIOS/build.cmake -I/home/adios/work/ADIOS/src -I/home/adios/work/ADIOS/src/core -I/home/adios/work/ADIOS/src/core/transforms -I/home/adios/work/ADIOS/build.cmake/src -I/home/adios/work/ADIOS/build.cmake/src/public -I/home/adios/work/ADIOS/src/mxml/mxml-2.9  -g -O0 -fPIC -Wno-int-to-pointer-cast -Wno-pointer-to-int-cast    -D_INTERNAL -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_GNU_SOURCE -DMPICH_IGNORE_CXX_SEEK -D_NOMPI -I/opt/netcdf-4.4.0/include -I/opt/hdf5-1.8.17/include -DZLIB -I/usr/include -DBZIP2 -I/usr/include -DSZIP -I/opt/szip/include -DISOBAR -I/opt/isobar/include -DALACRITY -I/opt/alacrity/include -DZFP -I/home/adios/work/ADIOS/src/zfp/zfp-0.5.0/inc -DFASTBIT -I/opt/fastbit/include/fastbit    -I/usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent;/usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent/include;/usr/lib/openmpi/include;/usr/lib/openmpi/include/openmpi -I/opt/chaos/include -I/opt/hdf5-1.8.17-parallel/include -DZLIB -I/usr/include -DBZIP2 -I/usr/include -DSZIP -I/opt/szip/include -DISOBAR -I/opt/isobar/include -DALACRITY -I/opt/alacrity/include -DZFP -I/home/adios/work/ADIOS/src/zfp/zfp-0.5.0/inc -DFASTBIT -I/opt/fastbit/include/fastbit -o CMakeFiles/adios_internal_nompi.dir/core/mpidummy.c.o   -c /home/adios/work/ADIOS/src/core/mpidummy.c
gcc: fatal error: no input files
compilation terminated.
/bin/sh: 1: /usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent/include: Permission denied
/bin/sh: 1: /usr/lib/openmpi/include: Permission denied
/bin/sh: 1: /usr/lib/openmpi/include/openmpi: Permission denied
src/CMakeFiles/adios_internal_nompi.dir/build.make:62: recipe for target 'src/CMakeFiles/adios_internal_nompi.dir/core/mpidummy.c.o' failed
make[2]: *** [src/CMakeFiles/adios_internal_nompi.dir/core/mpidummy.c.o] Error 126

**Comment by pnorbert** [comment]
The settings for configuration for the above build are coming from ./cmake_init for adiosVM.

**Comment by psychocoderHPC** [comment]
it looks like [this line](https://github.com/ornladios/ADIOS/pull/108/files#diff-af3b638bc2a3e6c650974192a53c7291R1494) is the reason for the crash. I will fix it

**Comment by psychocoderHPC** [comment]
I updated the branch and removed the `;`

I tested only the C build, because I have no mpi for fortran avail.

**Comment by psychocoderHPC** [comment]
Where can I find the `adiosVM` image?

**Comment by pnorbert** [comment]
The cmake build has been fixed for 1.12, so these commits don't need to be merged. Let us know if you still have any issues with cmake build of the master branch.

**Pull request closed without merging**
