### PR TITLE
Skel lib: Python3

### PR DESCRIPTION
**Pull request by ax3l**
Transform the python scripts in `utils/skel/lib` with `2to3` to be python3 compatible.

### CODE REVIEW

**Comment by ax3l** [comment]
@pnorbert can you please check if still everything works as expected in Python 2.7?

**Comment by pnorbert** [comment]
Hi Axel, I am at IPDPS at the moment.
@jychoi-hpc <https://github.com/jychoi-hpc> @isosc If you have some time
this week, can you please check this PR?
Thanks
Norbert

**Comment by ax3l** [comment]
@jychoi-hpc @isosc can you please take a look at this PR? :-)

**Comment by jychoi-hpc** [comment]
Sorry for being late. I am not knowledgeable to check this. I think Jeremy probably can do this.

**Comment by ax3l** [comment]
Hi Jeremy, I discovered the issue when trying to install ADIOS in a python2 only environment.

The problem was probably causes be the `ad_config.py` file I also patched, but updating the other syntax as well is already a step forward - even if not all dependencies support Python3 as well. (Still works under Python2 anyway.)

**Comment by isosc** [comment]
Sounds good, thanks!

**Pull request merged**
